name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e7d9be371f5f69ffbdb95226a17761b30780c6aa7b9b8b637a62dfed222481d"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
