name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "268ad98fee8f93bf73ab4134257aff3694fdf771fb5544c5a8d2f22014eec5be"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
