name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85cb3fabfa6cc48db301c1b7062f0af871b1bd53d73eb639b6b95035a1dcc9d9"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
