name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a53939b81179737afcb0c23e8983f2da098469ad2975d1dcb87a2f5a511422b4"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
