name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08bbb210c2f78eb6d9c3c1a37becb100700920313073034109524a2e8b40ca5f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
