name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7aa4ab4676cbe27e56c82f6aa5e140d95bc04aa65d40ff3c5a22e7053161a51"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
