name = "Unnamed Project ATM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c74cd660a19864cfb41a912af3f6db9eee69158dca8daba70a8747e9c9a13f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
